### ISSUE TITLE
VTK conda badge has 0/month

### ISSUE THREAD

**Issue by thewtex** [pyviz/website#30]
The VTK conda badge:

  https://pyviz-dev.github.io/website/_static/cache/VTK_conda_downloads_badge.svg

is currently listing 0/month. The badge here is working:

  https://github.com/conda-forge/vtk-feedstock

@jsignell any ideas?

**Comment by jsignell** [comment]
Jut to note that the badge at https://img.shields.io/conda/dn/conda-forge/vtk.svg is not showing the same thing because it shows the total downloads and the one on pyviz.org shows downloads in the last month. 

However yes, the computation was doing a bad job with case. I fixed it in #33. Sorry about that!

<img width="1192" alt="Screen Shot 2019-07-13 at 3 40 07 PM" src="https://user-images.githubusercontent.com/4806877/61176324-852b8a00-a584-11e9-98d1-0756fd1a1b86.png">

**Comment by jsignell** [comment]
Closed by #33
